//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSE_SE_XmlLinqPractice.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSE_SE_XmlLinqPractice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;line num=&quot;0&quot;&gt;
        ///    &lt;word num=&quot;0&quot; num2=&quot;0&quot;&gt;привет&lt;/word&gt;
        ///  &lt;/line&gt;
        ///  &lt;line num=&quot;1&quot;&gt;
        ///    &lt;word num=&quot;0&quot;&gt;как&lt;/word&gt;
        ///    &lt;word num=&quot;1&quot; num2=&quot;0&quot;&gt;дела&lt;/word&gt;
        ///  &lt;/line&gt;
        ///  &lt;line num=&quot;2&quot;&gt;
        ///    &lt;word num=&quot;0&quot;&gt;тест&lt;/word&gt;
        ///    &lt;word num=&quot;1&quot; num2=&quot;0&quot;&gt;для&lt;/word&gt;
        ///    &lt;word num=&quot;2&quot; num2=&quot;0&quot;&gt;практики&lt;/word&gt;
        ///  &lt;/line&gt;
        ///  &lt;line num=&quot;3&quot;&gt;
        ///    &lt;word num=&quot;0&quot;&gt;132&lt;/word&gt;
        ///    &lt;word num=&quot;1&quot;&gt;4223&lt;/word&gt;
        ///  &lt;/line&gt;
        ///  &lt;line num=&quot;4&quot;&gt;
        ///    &lt;word num=&quot;0&quot;&gt;ку&lt;/word&gt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string num15 {
            get {
                return ResourceManager.GetString("num15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на привет
        ///как дела
        ///тест для практики
        ///132 4223
        ///ку ку ку ку ку ку.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
